# Generated by Django 4.0.2 on 2022-03-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_first_name_alter_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_name',
            field=models.CharField(max_length=20),
        ),
    ]
